[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
hashkey_testnet = "${HSK_RPC_URL}"
sepolia = "${SEP_RPC_URL}"

[profile.networks.hashkey_testnet]
chain_id = 133

[profile.networks.sepolia]
chain_id = 11155111